export interface Medicine {
  id: string;
  name: string;
  category?: string;
  dosageForm?: string;
  strength?: string;
}

export const mockMedicines: Medicine[] = [
  // Pain Relief & Anti-inflammatory
  {
    id: "1",
    name: "بانادول اكسترا",
    category: "مسكنات",
    dosageForm: "أقراص",
    strength: "500مجم",
  },
  {
    id: "2",
    name: "أدفيل",
    category: "مسكنات",
    dosageForm: "كبسولات",
    strength: "400مجم",
  },
  {
    id: "3",
    name: "أسبيرين",
    category: "مسكنات",
    dosageForm: "أقراص",
    strength: "100مجم",
  },
  {
    id: "4",
    name: "بروفين",
    category: "مسكنات",
    dosageForm: "أقراص",
    strength: "200مجم",
  },
  {
    id: "5",
    name: "فولتارين",
    category: "مسكنات",
    dosageForm: "أقراص",
    strength: "50مجم",
  },
  {
    id: "6",
    name: "كاتافلام",
    category: "مسكنات",
    dosageForm: "أقراص",
    strength: "50مجم",
  },
  {
    id: "7",
    name: "أليف",
    category: "مسكنات",
    dosageForm: "أقراص",
    strength: "220مجم",
  },
  {
    id: "8",
    name: "سيرالكس",
    category: "مسكنات",
    dosageForm: "أقراص",
    strength: "100مجم",
  },

  // Antibiotics
  {
    id: "9",
    name: "أوجمنتين",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "1جم",
  },
  {
    id: "10",
    name: "زيثروماكس",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "500مجم",
  },
  {
    id: "11",
    name: "أموكسيسيلين",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "500مجم",
  },
  {
    id: "12",
    name: "سيبروفلوكساسين",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "500مجم",
  },
  {
    id: "13",
    name: "كلاريثروميسين",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "500مجم",
  },
  {
    id: "14",
    name: "دوكسيسيكلين",
    category: "مضادات حيوية",
    dosageForm: "كبسولات",
    strength: "100مجم",
  },
  {
    id: "15",
    name: "أزيثروميسين",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "250مجم",
  },
  {
    id: "16",
    name: "ليفوفلوكساسين",
    category: "مضادات حيوية",
    dosageForm: "أقراص",
    strength: "500مجم",
  },

  // Cold & Flu
  {
    id: "17",
    name: "سيتامول",
    category: "مسكنات",
    dosageForm: "شراب",
    strength: "120مجم/5مل",
  },
  {
    id: "18",
    name: "كونتراك",
    category: "مزيلات احتقان",
    dosageForm: "أقراص",
    strength: "400مجم",
  },
  {
    id: "19",
    name: "أكتيفيد",
    category: "مضادات هيستامين",
    dosageForm: "أقراص",
    strength: "8مجم",
  },
  {
    id: "20",
    name: "كلاريتين",
    category: "مضادات هيستامين",
    dosageForm: "أقراص",
    strength: "10مجم",
  },
  {
    id: "21",
    name: "زيرتيك",
    category: "مضادات هيستامين",
    dosageForm: "أقراص",
    strength: "10مجم",
  },
  {
    id: "22",
    name: "أليرجيك",
    category: "مضادات هيستامين",
    dosageForm: "شراب",
    strength: "2مجم/5مل",
  },

  // Gastrointestinal
  {
    id: "23",
    name: "أوميبرازول",
    category: "مضادات حموضة",
    dosageForm: "كبسولات",
    strength: "20مجم",
  },
  {
    id: "24",
    name: "بانتوبرازول",
    category: "مضادات حموضة",
    dosageForm: "أقراص",
    strength: "40مجم",
  },
  {
    id: "25",
    name: "رانيتيدين",
    category: "مضادات حموضة",
    dosageForm: "أقراص",
    strength: "150مجم",
  },
  {
    id: "26",
    name: "فاموتيدين",
    category: "مضادات حموضة",
    dosageForm: "أقراص",
    strength: "20مجم",
  },
  {
    id: "27",
    name: "موتيليوم",
    category: "منشطات حركة",
    dosageForm: "أقراص",
    strength: "10مجم",
  },

  // Cardiovascular
  {
    id: "28",
    name: "لوزارتان",
    category: "ضغط دم",
    dosageForm: "أقراص",
    strength: "50مجم",
  },
  {
    id: "29",
    name: "أموديبيين",
    category: "ضغط دم",
    dosageForm: "أقراص",
    strength: "5مجم",
  },
  {
    id: "30",
    name: "إنالابريل",
    category: "ضغط دم",
    dosageForm: "أقراص",
    strength: "10مجم",
  },
  {
    id: "31",
    name: "أتينولول",
    category: "ضغط دم",
    dosageForm: "أقراص",
    strength: "50مجم",
  },
  {
    id: "32",
    name: "بروبرانولول",
    category: "ضغط دم",
    dosageForm: "أقراص",
    strength: "40مجم",
  },
  {
    id: "33",
    name: "أسبيرين قلبي",
    category: "مضادات تخثر",
    dosageForm: "أقراص",
    strength: "81مجم",
  },
  {
    id: "34",
    name: "بلافيكس",
    category: "مضادات تخثر",
    dosageForm: "أقراص",
    strength: "75مجم",
  },

  // Diabetes
  {
    id: "35",
    name: "ميتفورمين",
    category: "سكري",
    dosageForm: "أقراص",
    strength: "500مجم",
  },
  {
    id: "36",
    name: "جليكلازيد",
    category: "سكري",
    dosageForm: "أقراص",
    strength: "80مجم",
  },
  {
    id: "37",
    name: "أنسولين لانتوس",
    category: "سكري",
    dosageForm: "حقن",
    strength: "100 وحدة/مل",
  },
  {
    id: "38",
    name: "أنسولين هيومالوج",
    category: "سكري",
    dosageForm: "حقن",
    strength: "100 وحدة/مل",
  },
  {
    id: "39",
    name: "جليمبيريد",
    category: "سكري",
    dosageForm: "أقراص",
    strength: "4مجم",
  },
  {
    id: "40",
    name: "بيوجليتازون",
    category: "سكري",
    dosageForm: "أقراص",
    strength: "30مجم",
  },

  // Vitamins & Supplements
  {
    id: "41",
    name: "فيتامين د",
    category: "فيتامينات",
    dosageForm: "كبسولات",
    strength: "1000 وحدة",
  },
  {
    id: "42",
    name: "فيتامين سي",
    category: "فيتامينات",
    dosageForm: "أقراص",
    strength: "500مجم",
  },
  {
    id: "43",
    name: "كالسيوم",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "600مجم",
  },
  {
    id: "44",
    name: "حديد",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "65مجم",
  },
  {
    id: "45",
    name: "زنك",
    category: "مكملات",
    dosageForm: "أقراص",
    strength: "50مجم",
  },
  {
    id: "46",
    name: "فيتامين ب المركب",
    category: "فيتامينات",
    dosageForm: "أقراص",
    strength: "مركب",
  },
  {
    id: "47",
    name: "أوميغا 3",
    category: "مكملات",
    dosageForm: "كبسولات",
    strength: "1000مجم",
  },
  {
    id: "48",
    name: "حمض الفوليك",
    category: "فيتامينات",
    dosageForm: "أقراص",
    strength: "400مكجم",
  },

  // Dermatology
  {
    id: "49",
    name: "كريم هيدروكورتيزون",
    category: "جلدية",
    dosageForm: "كريم",
    strength: "1%",
  },
  {
    id: "50",
    name: "كريم كلوتريمازول",
    category: "جلدية",
    dosageForm: "كريم",
    strength: "1%",
  },
  {
    id: "51",
    name: "بنزويل بيروكسايد",
    category: "جلدية",
    dosageForm: "جل",
    strength: "5%",
  },
  {
    id: "52",
    name: "كريم إيوسين",
    category: "جلدية",
    dosageForm: "كريم",
    strength: "2%",
  },
  {
    id: "53",
    name: "كريم نيفين",
    category: "جلدية",
    dosageForm: "كريم",
    strength: "مركب",
  },

  // Eye & Ear
  {
    id: "54",
    name: "قطرة توباماكس",
    category: "عين",
    dosageForm: "قطرة",
    strength: "0.5%",
  },
  {
    id: "55",
    name: "قطرة زاديتين",
    category: "عين",
    dosageForm: "قطرة",
    strength: "مركب",
  },
  {
    id: "56",
    name: "قطرة أوتوفين",
    category: "أذن",
    dosageForm: "قطرة",
    strength: "مركب",
  },
  {
    id: "57",
    name: "مرهم تتراسيكلين",
    category: "عين",
    dosageForm: "مرهم",
    strength: "1%",
  },

  // Respiratory
  {
    id: "58",
    name: "فنتولين",
    category: "ربو",
    dosageForm: "بخاخ",
    strength: "100مكجم",
  },
  {
    id: "59",
    name: "سيرفينت",
    category: "ربو",
    dosageForm: "بخاخ",
    strength: "250مكجم",
  },
  {
    id: "60",
    name: "سبيريفا",
    category: "ربو",
    dosageForm: "بخاخ",
    strength: "18مكجم",
  },
  {
    id: "61",
    name: "كومبيفينت",
    category: "ربو",
    dosageForm: "بخاخ",
    strength: "مركب",
  },

  // Neurology
  {
    id: "62",
    name: "فلوكستين",
    category: "مضادات اكتئاب",
    dosageForm: "كبسولات",
    strength: "20مجم",
  },
  {
    id: "63",
    name: "سيرتالين",
    category: "مضادات اكتئاب",
    dosageForm: "أقراص",
    strength: "50مجم",
  },
  {
    id: "64",
    name: "باروكستين",
    category: "مضادات اكتئاب",
    dosageForm: "أقراص",
    strength: "20مجم",
  },
  {
    id: "65",
    name: "ريسبيريدون",
    category: "مضادات ذهان",
    dosageForm: "أقراص",
    strength: "2مجم",
  },
  {
    id: "66",
    name: "جابابنتين",
    category: "مضادات تشنج",
    dosageForm: "كبسولات",
    strength: "300مجم",
  },

  // Hormones
  {
    id: "67",
    name: "ليفوثيروكسين",
    category: "هرمونات",
    dosageForm: "أقراص",
    strength: "100مكجم",
  },
  {
    id: "68",
    name: "ميثيل بريدنيزولون",
    category: "كورتيزون",
    dosageForm: "أقراص",
    strength: "4مجم",
  },
  {
    id: "69",
    name: "هيدروكورتيزون",
    category: "كورتيزون",
    dosageForm: "أقراص",
    strength: "10مجم",
  },
  {
    id: "70",
    name: "ديكساميثازون",
    category: "كورتيزون",
    dosageForm: "أقراص",
    strength: "0.5مجم",
  },

  // Additional Common Medications
  {
    id: "71",
    name: "وارفارين",
    category: "مضادات تخثر",
    dosageForm: "أقراص",
    strength: "5مجم",
  },
  {
    id: "72",
    name: "ديجوكسين",
    category: "قلب",
    dosageForm: "أقراص",
    strength: "0.25مجم",
  },
  {
    id: "73",
    name: "فيوروسيميد",
    category: "مدرات بول",
    dosageForm: "أقراص",
    strength: "40مجم",
  },
  {
    id: "74",
    name: "سبينورولاكتون",
    category: "مدرات بول",
    dosageForm: "أقراص",
    strength: "25مجم",
  },
  {
    id: "75",
    name: "ألوبورينول",
    category: "نقرس",
    dosageForm: "أقراص",
    strength: "300مجم",
  },
  {
    id: "76",
    name: "كولشيسين",
    category: "نقرس",
    dosageForm: "أقراص",
    strength: "0.5مجم",
  },
  {
    id: "77",
    name: "كاربامازيبين",
    category: "مضادات تشنج",
    dosageForm: "أقراص",
    strength: "200مجم",
  },
  {
    id: "78",
    name: "فالبرويك أسيد",
    category: "مضادات تشنج",
    dosageForm: "أقراص",
    strength: "500مجم",
  },
  {
    id: "79",
    name: "ليفوثيروكسين",
    category: "هرمونات",
    dosageForm: "أقراص",
    strength: "50مكجم",
  },
  {
    id: "80",
    name: "كالسيتريول",
    category: "فيتامينات",
    dosageForm: "كبسولات",
    strength: "0.25مكجم",
  },
];

// Generate additional medicines to reach a comprehensive sample size
const additionalMedicines = [
  // More Antibiotics
  "إريثروميسين",
  "كلينداميسين",
  "فانكومايسين",
  "ميترونيدازول",
  "تيتراسيكلين",
  "بنسيلين",
  "أمبيسيلين",
  "نافسيلين",
  "أوكزاسيلين",
  "ديكلوكساسين",
  "ميثيسيلين",
  "تيكارسيلين",

  // More Cardiovascular
  "أتورفاستاتين",
  "سيمفاستاتين",
  "روزوفاستاتين",
  "لوفاستاتين",
  "برافاستاتين",
  "نياسين",
  "فينوفايبريت",
  "جيمفيبروزيل",
  "كوليستيرامين",
  "كوليستيبول",
  "أليسكرين",
  "وارفارين",

  // More Gastrointestinal
  "سيميتيدين",
  "نيزاتيدين",
  "سوكرفالات",
  "ميزوبروستول",
  "أوميبرازول",
  "لانسوبرازول",
  "رابيبرازول",
  "إسوميبرازول",
  "ديكستروميثورفان",
  "لوبيراميد",
  "بسموث سبساليسيلات",

  // More Pain Relief
  "نابروكسين",
  "كيتورولاك",
  "ميلوكسيكام",
  "بيروكسيكام",
  "ديكلوفيناك",
  "إندوميثاسين",
  "نابوميتون",
  "سولينداك",
  "تولميتين",
  "فلوربيبروفين",
  "كيتوبروفين",
  "أوكسابروزين",

  // More Respiratory
  "سالبيوتامول",
  "تيربوتالين",
  "فينوتيرول",
  "فورموتيرول",
  "سالميتيرول",
  "إبراتروبيوم",
  "تيوتروبيوم",
  "أكليدينيوم",
  "جليكوبيرونيوم",
  "تيوفيلين",
  "أمينوفيلين",
  "مونتيلوكاست",

  // More Neuro/Psychiatric
  "ألبرازولام",
  "لورازيبام",
  "ديازيبام",
  "كلونازيبام",
  "تمازيبام",
  "أوكسازيبام",
  "كلونيدين",
  "بروبرانولول",
  "أميتريبتيلين",
  "نورتريبتيلين",
  "إيميبرامين",
  "ديسيبرامين",

  // More Endocrine
  "جليبيزيد",
  "جليبيزيد",
  "تولبوتاميد",
  "كلوربروباميد",
  "جليبوريد",
  "أكاربوز",
  "بيوجليتازون",
  "روجليتازون",
  "إكسيناتيد",
  "سيتاجليبتين",
  "فيلداجليبتين",
  "ليناجليبتين",

  // More Vitamins/Supplements
  "فيتامين أ",
  "فيتامين هـ",
  "فيتامين ك",
  "ثيامين",
  "ريبوفلافين",
  "نياسيناميد",
  "بيريدوكسين",
  "سيانوكوبالامين",
  "بيوتين",
  "بانتوثنيك أسيد",
  "كولين",
  "إينوزيتول",

  // More Dermatological
  "كينوكرين",
  "كبريتات زنك",
  "ساليسيليك أسيد",
  "ريزورسينول",
  "كالامين",
  "تلفا",
  "أكرتين",
  "أدابالين",
  "بنزويل بيروكسايد",
  "أزيليك أسيد",
  "كبريتات نحاس",
  "جنتيان فيوليت",

  // More Eye Medications
  "أتروبين",
  "تروبيكاميد",
  "سيكلوبنتولات",
  "هوماتروبين",
  "فينيليفرين",
  "تيمولول",
  "لاتانوبروست",
  "بيماتوبروست",
  "تافلوبروست",
  "بروبرانولول",
  "أسيكلوفير",
  "جنتاميسين",

  // More Pediatric
  "باراسيتامول شراب",
  "إيبوبروفين شراب",
  "أموكسيسيلين شراب",
  "أزيثروميسين شراب",
  "سيتالوبرام شراب",
  "فيتامين د قطرات",
  "فيتامين أ قطرات",
  "حديد قطرات",
  "زنك قطرات",
  "كالسيوم شراب",
  "مغنيسيوم شراب",
];

// Generate 120 additional medicines (IDs 81-200)
for (let i = 0; i < additionalMedicines.length; i++) {
  const medicineName = additionalMedicines[i];
  const categories = [
    "مضادات حيوية",
    "مسكنات",
    "ضغط دم",
    "سكري",
    "فيتامينات",
    "جلدية",
    "ربو",
    "قلب",
    "مكملات",
    "هرمونات",
  ];
  const dosageForms = [
    "أقراص",
    "كبسولات",
    "شراب",
    "حقن",
    "كريم",
    "مرهم",
    "قطرة",
    "بخاخ",
    "جل",
  ];
  const strengths = [
    "100مجم",
    "200مجم",
    "500مجم",
    "1جم",
    "5مجم",
    "10مجم",
    "20مجم",
    "50مجم",
    "0.5%",
    "1%",
    "2%",
    "5%",
  ];

  mockMedicines.push({
    id: (81 + i).toString(),
    name: medicineName,
    category: categories[Math.floor(Math.random() * categories.length)],
    dosageForm: dosageForms[Math.floor(Math.random() * dosageForms.length)],
    strength: strengths[Math.floor(Math.random() * strengths.length)],
  });
}
