import type { Purchase, PurchaseInvoice } from "../types";

export const purchasesMock: Purchase[] = [
  {
    id: "1",
    serialNumber: 1,
    invoiceNumber: "INV-001",
    invoiceDate: "2026-02-01",
    supplierId: "1",
    supplierName: "مؤسسة الأدوية المتحدة",
    total: 5000,
    status: "PAID",
  },
  {
    id: "2",
    serialNumber: 2,
    invoiceNumber: "INV-002",
    invoiceDate: "2026-02-05",
    supplierId: "2",
    supplierName: "مستودع الأدوية المركزي",
    total: 3000,
    status: "PENDING",
  },
  {
    id: "3",
    serialNumber: 3,
    invoiceNumber: "INV-003",
    invoiceDate: "2026-02-06",
    supplierId: "1",
    supplierName: "مؤسسة الأدوية المتحدة",
    total: 1200,
    status: "OVERDUE",
  },
  {
    id: "4",
    serialNumber: 4,
    invoiceNumber: "INV-004",
    invoiceDate: "2026-02-08",
    supplierId: "3",
    supplierName: "أحمد محمد العلي",
    total: 8500,
    status: "PAID",
  },
  {
    id: "5",
    serialNumber: 5,
    invoiceNumber: "INV-005",
    invoiceDate: "2026-02-10",
    supplierId: "2",
    supplierName: "مستودع الأدوية المركزي",
    total: 4200,
    status: "PENDING",
  },
  {
    id: "6",
    serialNumber: 6,
    invoiceNumber: "INV-006",
    invoiceDate: "2026-01-25",
    supplierId: "4",
    supplierName: "شركة النور للتجارة",
    total: 6700,
    status: "OVERDUE",
  },
];

// Mock data for detailed invoices
export const mockPurchaseInvoices: PurchaseInvoice[] = [
  {
    id: "1",
    invoiceNumber: "INV-001",
    invoiceDate: "2026-02-01",
    supplierId: "1",
    supplierName: "مؤسسة الأدوية المتحدة",
    notes: "فاتورة مشتريات أدوية أساسية للشهر",
    items: [
      {
        id: "1",
        medicineCode: "MED001",
        medicineName: "بانادول إكسترا",
        quantity: 100,
        unitsPerPackage: 24,
        salePrice: 45.5,
        tax: 14,
        mainDiscount: 5,
        extraDiscount: 2,
        cost: 35.2,
        expiryDate: "2028-12-31",
        bonus: 5,
        expirable: true,
      },
      {
        id: "2",
        medicineCode: "MED002",
        medicineName: "أوجمنتين 625 مجم",
        quantity: 50,
        unitsPerPackage: 14,
        salePrice: 85.0,
        tax: 14,
        mainDiscount: 3,
        extraDiscount: 0,
        cost: 72.5,
        expiryDate: "2027-08-15",
        bonus: 0,
        expirable: true,
      },
      {
        id: "3",
        medicineCode: "MED003",
        medicineName: "فولتارين 50 مجم",
        quantity: 75,
        unitsPerPackage: 20,
        salePrice: 28.75,
        tax: 14,
        mainDiscount: 4,
        extraDiscount: 1,
        cost: 22.3,
        expiryDate: "2029-03-20",
        bonus: 3,
        expirable: true,
      },
    ],
    totals: {
      itemsValue: 8500,
      profitPercentage: 22.5,
      total: 5000,
      baseTotal: 4500,
      taxTotal: 700,
      extraCosts: 200,
      extraDiscount: 100,
    },
  },
  {
    id: "2",
    invoiceNumber: "INV-002",
    invoiceDate: "2026-02-05",
    supplierId: "2",
    supplierName: "مستودع الأدوية المركزي",
    notes: "مشتريات من المستودع المركزي",
    items: [
      {
        id: "4",
        medicineCode: "MED004",
        medicineName: "أموكسيل 500 مجم",
        quantity: 120,
        unitsPerPackage: 24,
        salePrice: 25.0,
        tax: 14,
        mainDiscount: 6,
        extraDiscount: 0,
        cost: 18.5,
        expiryDate: "2028-06-30",
        bonus: 8,
        expirable: true,
      },
      {
        id: "5",
        medicineCode: "MED005",
        medicineName: "بروفين 400 مجم",
        quantity: 80,
        unitsPerPackage: 20,
        salePrice: 32.0,
        tax: 14,
        mainDiscount: 4,
        extraDiscount: 1,
        cost: 26.8,
        expiryDate: "2029-01-15",
        bonus: 0,
        expirable: true,
      },
    ],
    totals: {
      itemsValue: 4800,
      profitPercentage: 18.5,
      total: 3000,
      baseTotal: 2800,
      taxTotal: 420,
      extraCosts: 150,
      extraDiscount: 50,
    },
  },
  {
    id: "3",
    invoiceNumber: "INV-003",
    invoiceDate: "2026-02-06",
    supplierId: "1",
    supplierName: "مؤسسة الأدوية المتحدة",
    notes: "فاتورة متأخرة - تحتاج للمتابعة",
    items: [
      {
        id: "6",
        medicineCode: "MED006",
        medicineName: "زينتاك 150 مجم",
        quantity: 60,
        unitsPerPackage: 14,
        salePrice: 55.0,
        tax: 14,
        mainDiscount: 5,
        extraDiscount: 0,
        cost: 42.5,
        expiryDate: "2027-12-20",
        bonus: 4,
        expirable: true,
      },
    ],
    totals: {
      itemsValue: 1800,
      profitPercentage: 20.0,
      total: 1200,
      baseTotal: 1100,
      taxTotal: 154,
      extraCosts: 50,
      extraDiscount: 0,
    },
  },
  {
    id: "4",
    invoiceNumber: "INV-004",
    invoiceDate: "2026-02-08",
    supplierId: "3",
    supplierName: "أحمد محمد العلي",
    notes: "مشتريات من مورد فردي",
    items: [
      {
        id: "7",
        medicineCode: "MED007",
        medicineName: "فلاجيل 400 مجم",
        quantity: 200,
        unitsPerPackage: 20,
        salePrice: 15.0,
        tax: 14,
        mainDiscount: 8,
        extraDiscount: 2,
        cost: 11.2,
        expiryDate: "2028-09-10",
        bonus: 15,
        expirable: true,
      },
      {
        id: "8",
        medicineCode: "MED008",
        medicineName: "سبازموسيلفان 2 مجم",
        quantity: 150,
        unitsPerPackage: 50,
        salePrice: 8.5,
        tax: 14,
        mainDiscount: 3,
        extraDiscount: 0,
        cost: 6.8,
        expiryDate: "2029-05-25",
        bonus: 0,
        expirable: true,
      },
    ],
    totals: {
      itemsValue: 12000,
      profitPercentage: 25.5,
      total: 8500,
      baseTotal: 7500,
      taxTotal: 1050,
      extraCosts: 300,
      extraDiscount: 200,
    },
  },
  {
    id: "5",
    invoiceNumber: "INV-005",
    invoiceDate: "2026-02-10",
    supplierId: "2",
    supplierName: "مستودع الأدوية المركزي",
    notes: "مشتريات إضافية للشهر",
    items: [
      {
        id: "9",
        medicineCode: "MED009",
        medicineName: "كيتوفان 50 مجم",
        quantity: 90,
        unitsPerPackage: 10,
        salePrice: 75.0,
        tax: 14,
        mainDiscount: 7,
        extraDiscount: 1,
        cost: 58.5,
        expiryDate: "2028-11-30",
        bonus: 6,
        expirable: true,
      },
    ],
    totals: {
      itemsValue: 7200,
      profitPercentage: 22.0,
      total: 5200,
      baseTotal: 4800,
      taxTotal: 672,
      extraCosts: 200,
      extraDiscount: 100,
    },
  },
];

// Function to get invoice by ID
export const getPurchaseInvoiceById = (id: string): PurchaseInvoice | null => {
  return mockPurchaseInvoices.find((invoice) => invoice.id === id) || null;
};

// Function to delete a purchase (simulated - doesn't actually delete from array)
export const deletePurchase = (id: string): boolean => {
  const index = purchasesMock.findIndex((p) => p.id === id);
  if (index !== -1) {
    // Simulate deletion but don't actually remove from array
    console.log(`Simulating deletion of purchase with id ${id}`);
    console.log(
      `Purchase found at index ${index}, but keeping it for simulation`,
    );
    console.log(`Total items remain: ${purchasesMock.length}`);
    return true; // Simulate successful deletion
  }
  console.log(`Purchase with id ${id} not found`);
  return false;
};
