import type { Customer } from "../types";

export const mockCustomers: Customer[] = [
  {
    id: "1",
    name: "أحمد محمد العلي",
    phone: "0501234567",
    address: "الرياض، حي النخيل",
    type: "فرد",
    isCashOnly: false,
    balance: -1500.5,
    creditLimit: 5000,
    localDiscount: 5,
    importDiscount: 3,
    lastTransactionAt: "2024-01-15T10:30:00Z",
    loyalty: {
      id: "loyalty-1",
      pointsPerCurrency: 1,
      totalPoints: 250,
      pendingPoints: 25,
    },
  },
  {
    id: "2",
    name: "شركة النور للتجارة",
    phone: "0112345678",
    address: "جدة، حي الروضة",
    type: "شركة",
    isCashOnly: false,
    balance: 8500.75,
    creditLimit: 20000,
    localDiscount: 10,
    importDiscount: 7,
    lastTransactionAt: "2024-01-14T14:20:00Z",
    loyalty: {
      id: "loyalty-2",
      pointsPerCurrency: 2,
      totalPoints: 1200,
      pendingPoints: 150,
    },
  },
  {
    id: "3",
    name: "فاطمة عبدالله السعيد",
    phone: "0559876543",
    address: "الدمام، حي الأمل",
    type: "فرد",
    isCashOnly: true,
    balance: 0,
    creditLimit: 0,
    localDiscount: 2,
    importDiscount: 1,
    lastTransactionAt: "2024-01-13T09:15:00Z",
    loyalty: {
      id: "loyalty-3",
      pointsPerCurrency: 1,
      totalPoints: 85,
      pendingPoints: 10,
    },
  },
  {
    id: "4",
    name: "محمد خالد الرشيد",
    phone: "0563456789",
    address: "مكة المكرمة، حي الشوقية",
    type: "فرد",
    isCashOnly: false,
    balance: -3200.0,
    creditLimit: 10000,
    localDiscount: 7,
    importDiscount: 4,
    lastTransactionAt: "2024-01-12T16:45:00Z",
    loyalty: {
      id: "loyalty-4",
      pointsPerCurrency: 1,
      totalPoints: 450,
      pendingPoints: 50,
    },
  },
  {
    id: "5",
    name: "مؤسسة الأفق للخدمات الطبية",
    phone: "0123456789",
    address: "المدينة المنورة، حي العزيزية",
    type: "شركة",
    isCashOnly: false,
    balance: 12500.25,
    creditLimit: 50000,
    localDiscount: 15,
    importDiscount: 10,
    lastTransactionAt: "2024-01-11T11:30:00Z",
    loyalty: {
      id: "loyalty-5",
      pointsPerCurrency: 3,
      totalPoints: 2500,
      pendingPoints: 300,
    },
  },
  {
    id: "6",
    name: "نورة سالم القحطاني",
    phone: "0545678901",
    address: "الطائف، حي الصفا",
    type: "فرد",
    isCashOnly: true,
    balance: 0,
    creditLimit: 0,
    localDiscount: 3,
    importDiscount: 2,
    lastTransactionAt: "2024-01-10T13:20:00Z",
    loyalty: {
      id: "loyalty-6",
      pointsPerCurrency: 1,
      totalPoints: 120,
      pendingPoints: 15,
    },
  },
  {
    id: "7",
    name: "عبدالرحمن أحمد العنزي",
    phone: "0578901234",
    address: "تبوك، حي الجامعة",
    type: "فرد",
    isCashOnly: false,
    balance: -800.3,
    creditLimit: 3000,
    localDiscount: 4,
    importDiscount: 2,
    lastTransactionAt: "2024-01-09T15:10:00Z",
    loyalty: {
      id: "loyalty-7",
      pointsPerCurrency: 1,
      totalPoints: 200,
      pendingPoints: 20,
    },
  },
  {
    id: "8",
    name: "شركة الرائد للتوريدات",
    phone: "0134567890",
    address: "الخبر، حي العزيزية",
    type: "شركة",
    isCashOnly: false,
    balance: 22000.5,
    creditLimit: 75000,
    localDiscount: 12,
    importDiscount: 8,
    lastTransactionAt: "2024-01-08T10:45:00Z",
    loyalty: {
      id: "loyalty-8",
      pointsPerCurrency: 2,
      totalPoints: 1800,
      pendingPoints: 200,
    },
  },
  {
    id: "9",
    name: "سارة محمد الدوسري",
    phone: "0534567890",
    address: "حائل، حي الملك فهد",
    type: "فرد",
    isCashOnly: false,
    balance: -4500.75,
    creditLimit: 8000,
    localDiscount: 6,
    importDiscount: 3,
    lastTransactionAt: "2024-01-07T12:30:00Z",
    loyalty: {
      id: "loyalty-9",
      pointsPerCurrency: 1,
      totalPoints: 320,
      pendingPoints: 35,
    },
  },
  {
    id: "10",
    name: "خالد إبراهيم الشمري",
    phone: "0598765432",
    address: "نجران، حي الفيصلية",
    type: "فرد",
    isCashOnly: true,
    balance: 0,
    creditLimit: 0,
    localDiscount: 2,
    importDiscount: 1,
    lastTransactionAt: "2024-01-06T14:15:00Z",
    loyalty: {
      id: "loyalty-10",
      pointsPerCurrency: 1,
      totalPoints: 95,
      pendingPoints: 12,
    },
  },
  {
    id: "11",
    name: "مجموعة البركة للتجارة",
    phone: "0145678901",
    address: "جازان، حي النهضة",
    type: "شركة",
    isCashOnly: false,
    balance: 18500.0,
    creditLimit: 40000,
    localDiscount: 8,
    importDiscount: 5,
    lastTransactionAt: "2024-01-05T09:50:00Z",
    loyalty: {
      id: "loyalty-11",
      pointsPerCurrency: 2,
      totalPoints: 950,
      pendingPoints: 100,
    },
  },
  {
    id: "12",
    name: "هدى علي الحربي",
    phone: "0512345678",
    address: "القصيم، حي الناصرية",
    type: "فرد",
    isCashOnly: false,
    balance: -1200.6,
    creditLimit: 2500,
    localDiscount: 5,
    importDiscount: 3,
    lastTransactionAt: "2024-01-04T16:25:00Z",
    loyalty: {
      id: "loyalty-12",
      pointsPerCurrency: 1,
      totalPoints: 180,
      pendingPoints: 18,
    },
  },
  {
    id: "13",
    name: "يوسف عمر المالكي",
    phone: "0587654321",
    address: "الرياض، حي الياسمين",
    type: "فرد",
    isCashOnly: false,
    balance: -2100.25,
    creditLimit: 6000,
    localDiscount: 6,
    importDiscount: 4,
    lastTransactionAt: "2024-01-03T11:40:00Z",
    loyalty: {
      id: "loyalty-13",
      pointsPerCurrency: 1,
      totalPoints: 280,
      pendingPoints: 30,
    },
  },
  {
    id: "14",
    name: "شركة الأمل للدواء",
    phone: "0167890123",
    address: "الرياض، حي المروج",
    type: "شركة",
    isCashOnly: false,
    balance: 32000.75,
    creditLimit: 100000,
    localDiscount: 18,
    importDiscount: 12,
    lastTransactionAt: "2024-01-02T13:55:00Z",
    loyalty: {
      id: "loyalty-14",
      pointsPerCurrency: 3,
      totalPoints: 3200,
      pendingPoints: 350,
    },
  },
  {
    id: "15",
    name: "مريم عبدالعزيز الغامدي",
    phone: "0523456789",
    address: "أبها، حي المنكوب",
    type: "فرد",
    isCashOnly: true,
    balance: 0,
    creditLimit: 0,
    localDiscount: 3,
    importDiscount: 2,
    lastTransactionAt: "2024-01-01T10:20:00Z",
    loyalty: {
      id: "loyalty-15",
      pointsPerCurrency: 1,
      totalPoints: 110,
      pendingPoints: 12,
    },
  },
  {
    id: "16",
    name: "تركي فهد العتيبي",
    phone: "0567890123",
    address: "الجوف، حي الشمال",
    type: "فرد",
    isCashOnly: false,
    balance: -950.4,
    creditLimit: 4000,
    localDiscount: 5,
    importDiscount: 3,
    lastTransactionAt: "2023-12-31T15:30:00Z",
    loyalty: {
      id: "loyalty-16",
      pointsPerCurrency: 1,
      totalPoints: 165,
      pendingPoints: 18,
    },
  },
  {
    id: "17",
    name: "شركة الطب للخدمات الصحية",
    phone: "0178901234",
    address: "الدمام، حي الشاطئ",
    type: "شركة",
    isCashOnly: false,
    balance: 28500.9,
    creditLimit: 80000,
    localDiscount: 14,
    importDiscount: 9,
    lastTransactionAt: "2023-12-30T12:15:00Z",
    loyalty: {
      id: "loyalty-17",
      pointsPerCurrency: 2,
      totalPoints: 2100,
      pendingPoints: 220,
    },
  },
  {
    id: "18",
    name: "لطيفة حسن العنزي",
    phone: "0543210987",
    address: "حفر الباطن، حي الفيصل",
    type: "فرد",
    isCashOnly: false,
    balance: -1800.8,
    creditLimit: 5500,
    localDiscount: 7,
    importDiscount: 4,
    lastTransactionAt: "2023-12-29T14:45:00Z",
    loyalty: {
      id: "loyalty-18",
      pointsPerCurrency: 1,
      totalPoints: 240,
      pendingPoints: 25,
    },
  },
  {
    id: "19",
    name: "فيصل سعد الشهراني",
    phone: "0598765432",
    address: "الباحة، حي المركز",
    type: "فرد",
    isCashOnly: true,
    balance: 0,
    creditLimit: 0,
    localDiscount: 2,
    importDiscount: 1,
    lastTransactionAt: "2023-12-28T09:35:00Z",
    loyalty: {
      id: "loyalty-19",
      pointsPerCurrency: 1,
      totalPoints: 88,
      pendingPoints: 9,
    },
  },
  {
    id: "20",
    name: "مؤسسة الصحة للإمدادات الطبية",
    phone: "0189012345",
    address: "الخبر، حي النخيل",
    type: "شركة",
    isCashOnly: false,
    balance: 41000.25,
    creditLimit: 120000,
    localDiscount: 20,
    importDiscount: 15,
    lastTransactionAt: "2023-12-27T11:50:00Z",
    loyalty: {
      id: "loyalty-20",
      pointsPerCurrency: 4,
      totalPoints: 4100,
      pendingPoints: 420,
    },
  },
];

// Generate additional customers to reach 100 total (10 pages × 10 items per page)
const firstNames = [
  "أحمد",
  "محمد",
  "عبدالله",
  "عبدالرحمن",
  "خالد",
  "سعود",
  "فيصل",
  "تركي",
  "نايف",
  "بندر",
  "سلطان",
  "عمر",
  "علي",
  "حسن",
  "إبراهيم",
  "يوسف",
  "محمود",
  "عبدالعزيز",
  "سعد",
  "ناصر",
  "فهد",
  "مشاري",
  "راشد",
  "طلال",
  "غازي",
  "مسفر",
  "عبدالمجيد",
  "بدر",
  "حمد",
  "منصور",
  "ناصر",
  "هاني",
  "باسل",
  "معاذ",
  "أيمن",
  "عماد",
  "وسيم",
  "رائد",
  "أسامة",
  "مروان",
];

const lastNames = [
  "العلي",
  "السعيد",
  "الرشيد",
  "القحطاني",
  "العنزي",
  "الشمري",
  "الدوسري",
  "الغامدي",
  "العتيبي",
  "الحربي",
  "المالكي",
  "الشهراني",
  "البداح",
  "السبيعي",
  "الروقي",
  "العمري",
  "الحسين",
  "الخالدي",
  "الفهيد",
  "الصالح",
  "الزامل",
  "المطيري",
  "الجهني",
  "البقمي",
  "الشمراني",
  "العصيمي",
  "السالم",
  "الرشيد",
  "المنصور",
  "التركي",
];

const companyNames = [
  "شركة",
  "مؤسسة",
  "مجموعة",
  "شركة",
  "مؤسسة",
  "مجموعة",
  "شركة",
  "مؤسسة",
  "مجموعة",
  "شركة",
];

const companySuffixes = [
  "للتجارة",
  "للخدمات",
  "للإمدادات",
  "للتوريدات",
  "للدواء",
  "الطبية",
  "للصناعة",
  "للنقل",
  "للتوزيع",
  "للاستثمار",
];

const cities = [
  "الرياض",
  "جدة",
  "مكة المكرمة",
  "المدينة المنورة",
  "الدمام",
  "الخبر",
  "الطائف",
  "تبوك",
  "نجران",
  "حائل",
  "القصيم",
  "جازان",
  "أبها",
  "الباحة",
  "الجوف",
  "حفر الباطن",
  "العرين",
  "رفحاء",
  "طريف",
  "الوجه",
];

const districts = [
  "حي النخيل",
  "حي الروضة",
  "حي الأمل",
  "حي الشوقية",
  "حي العزيزية",
  "حي الصفا",
  "حي الجامعة",
  "حي المروج",
  "حي المنكوب",
  "حي الشمال",
  "حي الشاطئ",
  "حي الفيصل",
  "حي المركز",
  "حي النهضة",
  "حي الناصرية",
  "حي الياسمين",
  "حي الملك فهد",
  "حي الفيصلية",
  "حي العزيزية",
  "حي النخيل",
];

function generateRandomCustomer(id: string): Customer {
  const isCompany = Math.random() > 0.6;
  const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];
  const city = cities[Math.floor(Math.random() * cities.length)];
  const district = districts[Math.floor(Math.random() * districts.length)];

  const name = isCompany
    ? `${companyNames[Math.floor(Math.random() * companyNames.length)]} ${firstName} ${companySuffixes[Math.floor(Math.random() * companySuffixes.length)]}`
    : `${firstName} ${lastName}`;

  const phone = `05${Math.floor(Math.random() * 90000000) + 10000000}`;
  const address = `${city}، ${district}`;

  const balance =
    Math.random() > 0.5
      ? -(Math.random() * 5000 + 100)
      : Math.random() * 30000 + 1000;

  const creditLimit = isCompany
    ? Math.floor(Math.random() * 100000 + 20000)
    : Math.floor(Math.random() * 10000 + 1000);

  const localDiscount = Math.floor(Math.random() * 20);
  const importDiscount = Math.floor(Math.random() * 15);

  const daysAgo = Math.floor(Math.random() * 90);
  const lastTransactionDate = new Date();
  lastTransactionDate.setDate(lastTransactionDate.getDate() - daysAgo);

  return {
    id,
    name,
    phone,
    address,
    type: isCompany ? "شركة" : "فرد",
    isCashOnly: Math.random() > 0.7,
    balance,
    creditLimit,
    localDiscount,
    importDiscount,
    lastTransactionAt: lastTransactionDate.toISOString(),
    loyalty: {
      id: `loyalty-${id}`,
      pointsPerCurrency: Math.floor(Math.random() * 4) + 1,
      totalPoints: Math.floor(Math.random() * 5000 + 50),
      pendingPoints: Math.floor(Math.random() * 500 + 10),
    },
  };
}

// Generate 80 additional customers (IDs 21-100)
for (let i = 21; i <= 100; i++) {
  mockCustomers.push(generateRandomCustomer(i.toString()));
}
